# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e30d9ce06374b84c1fd47fc30946975431edbf29d9441f561f63fcf5bd0a828e1ea45d6b47058ab202868d01dc21812a924527ac9798426e7b034c4a06983ea7

test:
  secret_key_base: b8d5b622b1a9ee3d569e6eda9c8e9aac45684c71ffc27b39ed964164bd476d57203efa5246b4a7831ef7ccc2594f37215cea376fa22f6811030d7cb494478a5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
